# Generated by Django 4.1 on 2022-09-03 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField(max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('code', models.SlugField(max_length=60, null=True)),
                ('release', models.DateField()),
                ('casting', models.ManyToManyField(related_name='movie_actors', to=settings.AUTH_USER_MODEL)),
                ('directors', models.ManyToManyField(related_name='movie_directors', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='movie_genre', to='movie.genre')),
                ('producers', models.ManyToManyField(related_name='movie_producers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
