# Generated by Django 4.1 on 2022-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('enabled', 'enabled')], default='draft', max_length=10),
        ),
    ]
