# Generated by Django 4.1 on 2022-09-05 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(related_name='movie_casting', to=settings.AUTH_USER_MODEL),
        ),
    ]
